import { ShieldCheck, ShieldAlert, EyeOff, Activity, Download, Filter } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { MetricCard } from "@/components/metric-card";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { CoverageBar } from "@/components/coverage-bar";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { cn } from "@/lib/utils";
import { useGovernance, useGovernanceSummary } from "@/hooks/useGovernance";

export function GovernancePage() {
  const dbId = 1;
  const { data: summary } = useGovernanceSummary(dbId);
  const { data } = useGovernance(dbId);
  const packages = data?.packages ?? [];
  const rows = packages.flatMap((pkg) => pkg.pii_columns.map((c) => ({ table: `${pkg.schema_name}.${pkg.table_name}`, col: c.column_name, classification: c.pii_type ?? "PII", risk: c.risk_level ?? "medium", confidence: c.confidence_score ?? 0, purpose: c.business_meaning ?? pkg.business_purpose ?? "" })));
  const tableSummary = packages.map((pkg) => ({ name: `${pkg.schema_name}.${pkg.table_name}`, piiCols: pkg.pii_columns.length, highRisk: pkg.risk_columns.length, coverage: pkg.confidence_score ? Math.round(pkg.confidence_score * 100) : 0 }));
  const avgConfidence = packages.length ? (packages.reduce((a, p) => a + (p.confidence_score ?? 0), 0) / packages.length).toFixed(2) : "0.00";
  return (
    <div className="space-y-6">
      <PageHeader eyebrow="Intelligence" title="Governance" description="Live PII classifications, risk profile, and column-level business purpose from persisted governance packages." actions={<><Button variant="outline" size="sm" className="gap-1.5"><Filter className="h-3.5 w-3.5" /> Filter</Button><Button variant="outline" size="sm" className="gap-1.5"><Download className="h-3.5 w-3.5" /> Export package</Button></>} />
      <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Governance coverage" value={String(summary?.table_count ?? packages.length)} hint="tables with persisted packages" icon={ShieldCheck} progress={Math.min(100, summary?.governance_packages ? (summary.table_count / Math.max(1, summary.governance_packages)) * 100 : 0)} tone="success" /><MetricCard label="PII columns" value={String(summary?.pii_columns ?? 0)} hint="from live packages" icon={EyeOff} tone="warning" /><MetricCard label="High-risk columns" value={String(summary?.risk_columns ?? 0)} hint="recommend access policy" icon={ShieldAlert} tone="danger" /><MetricCard label="Avg confidence" value={avgConfidence} hint="persisted package confidence" icon={Activity} tone="info" /></section>
      <div className="grid grid-cols-1 gap-4 xl:grid-cols-3">
        <Card className="xl:col-span-2"><CardHeader><CardTitle className="text-base">Governance package</CardTitle><CardDescription>Column-level classifications generated for the active source.</CardDescription></CardHeader><CardContent><Tabs defaultValue="columns"><TabsList><TabsTrigger value="columns">Columns</TabsTrigger><TabsTrigger value="tables">Tables</TabsTrigger></TabsList><TabsContent value="columns" className="pt-4"><div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-muted/40 hover:bg-muted/40"><TableHead>Column</TableHead><TableHead>Classification</TableHead><TableHead>Risk</TableHead><TableHead className="text-right">Confidence</TableHead><TableHead>Business purpose</TableHead></TableRow></TableHeader><TableBody>{rows.length ? rows.map((r) => (<TableRow key={`${r.table}.${r.col}`}><TableCell><div className="text-sm"><span className="text-muted-foreground">{r.table}.</span><span className="font-medium text-foreground">{r.col}</span></div></TableCell><TableCell className="text-sm">{r.classification}</TableCell><TableCell><RiskBadge risk={r.risk as "high" | "medium" | "low"} /></TableCell><TableCell className="text-right tabular-nums text-sm">{r.confidence.toFixed(2)}</TableCell><TableCell className="text-xs text-muted-foreground">{r.purpose}</TableCell></TableRow>)) : <TableRow><TableCell colSpan={5} className="text-sm text-muted-foreground">No governance packages found for database 1.</TableCell></TableRow>}</TableBody></Table></div></TabsContent><TabsContent value="tables" className="pt-4"><Table><TableHeader><TableRow className="bg-muted/40 hover:bg-muted/40"><TableHead>Table</TableHead><TableHead className="text-right">PII cols</TableHead><TableHead className="text-right">High risk</TableHead><TableHead className="min-w-[180px]">Coverage</TableHead></TableRow></TableHeader><TableBody>{tableSummary.length ? tableSummary.map((t) => (<TableRow key={t.name}><TableCell className="font-mono text-sm">{t.name}</TableCell><TableCell className="text-right tabular-nums">{t.piiCols}</TableCell><TableCell className="text-right tabular-nums">{t.highRisk}</TableCell><TableCell><CoverageBar value={t.coverage} /></TableCell></TableRow>)) : <TableRow><TableCell colSpan={4} className="text-sm text-muted-foreground">No table summaries available.</TableCell></TableRow>}</TableBody></Table></TabsContent></Tabs></CardContent></Card>
        <Card><CardHeader><CardTitle className="text-base">Risk distribution</CardTitle><CardDescription>Across all classified columns.</CardDescription></CardHeader><CardContent className="space-y-4">{[{ label: "High risk", value: summary?.risk_columns ?? 0, total: summary?.pii_columns ?? 1, tone: "danger" as const }, { label: "Sensitive", value: summary?.sensitive_columns ?? 0, total: summary?.pii_columns ?? 1, tone: "warning" as const }, { label: "Low risk", value: Math.max(0, (summary?.pii_columns ?? 0) - (summary?.risk_columns ?? 0) - (summary?.sensitive_columns ?? 0)), total: summary?.pii_columns ?? 1, tone: "success" as const }].map((r) => (<div key={r.label}><div className="flex items-center justify-between text-xs"><span className="font-medium text-foreground">{r.label}</span><span className="tabular-nums text-muted-foreground">{r.value} / {r.total}</span></div><CoverageBar value={(r.value / Math.max(1, r.total)) * 100} tone={r.tone} className="mt-1.5" /></div>))}<div className="rounded-md border border-border bg-muted/30 p-3 text-xs text-muted-foreground">Recommended next step: apply masking policy to high-risk columns before exposing them to the agent layer.</div></CardContent></Card>
      </div>
    </div>
  );
}
function RiskBadge({ risk }: { risk: "high" | "medium" | "low" }) { return <Badge variant="outline" className={cn("rounded-full text-[10px] uppercase tracking-wider", risk === "high" && "border-destructive/40 bg-destructive/10 text-destructive", risk === "medium" && "border-[var(--warning)]/40 bg-[var(--warning)]/15 text-[var(--warning)]", risk === "low" && "border-[var(--success)]/40 bg-[var(--success)]/10 text-[var(--success)]")}>{risk}</Badge>; }
