import { Network, GitBranch, Workflow, Search, Layers } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CoverageBar } from "@/components/coverage-bar";
import { useRelationships } from "@/hooks/useRelationships";

export function RelationshipsPage() {
  const dbId = 1;
  const { data } = useRelationships(dbId);
  const clusters = data?.packages ?? [];
  return (<div className="space-y-6"><PageHeader eyebrow="Intelligence" title="Relationships" description="Cluster summaries, entity graph, hidden relationships, and lifecycle flows from persisted relationship packages." /><div className="grid grid-cols-1 gap-4 xl:grid-cols-1"><Card><CardHeader><CardTitle className="text-base">Relationship packages</CardTitle><CardDescription>Hidden relationships, process flows, and lifecycle dependencies.</CardDescription></CardHeader><CardContent><Tabs defaultValue="hidden"><TabsList><TabsTrigger value="hidden"><Search className="mr-1 h-3.5 w-3.5" /> Hidden</TabsTrigger><TabsTrigger value="processes"><Workflow className="mr-1 h-3.5 w-3.5" /> Process flows</TabsTrigger><TabsTrigger value="lifecycle"><GitBranch className="mr-1 h-3.5 w-3.5" /> Lifecycle</TabsTrigger><TabsTrigger value="deps"><Layers className="mr-1 h-3.5 w-3.5" /> Dependencies</TabsTrigger></TabsList><TabsContent value="hidden" className="space-y-2 pt-4">{clusters.length ? clusters.flatMap((c) => (c.hidden_relationships ?? []).map((r) => ({ cluster_id: c.cluster_id, relationship: r }))).slice(0, 8).map((item: any, i: number) => (<div key={`${item.cluster_id}-${i}`} className="flex flex-wrap items-center gap-3 rounded-md border border-border bg-card p-3"><Network className="h-4 w-4 text-primary" /><code className="text-xs text-foreground">{item.relationship.left ?? item.relationship.source ?? "unknown"}</code><span className="text-xs text-muted-foreground">↔</span><code className="text-xs text-foreground">{item.relationship.right ?? item.relationship.target ?? "unknown"}</code><span className="ml-auto text-[11px] text-muted-foreground">{item.relationship.note ?? item.relationship.summary ?? "persisted hidden relationship"}</span></div>)) : <div className="text-sm text-muted-foreground">No relationship packages found yet.</div>}</TabsContent><TabsContent value="processes" className="pt-4 text-sm text-muted-foreground">{clusters.length ? (clusters[0].business_process_flows?.map((p: any) => p.summary ?? JSON.stringify(p)) ?? []).join(" • ") : "No process flows available."}</TabsContent><TabsContent value="lifecycle" className="pt-4 text-sm text-muted-foreground">{clusters.length ? (clusters[0].lifecycle_flows?.map((p: any) => p.summary ?? JSON.stringify(p)) ?? []).join(" • ") : "No lifecycle flows available."}</TabsContent><TabsContent value="deps" className="pt-4 text-sm text-muted-foreground">{clusters.length ? (<div className="space-y-2">{clusters.slice(0, 5).map((c) => (<div key={c.cluster_id} className="rounded-md border border-border bg-card p-3"><div className="text-sm font-medium text-foreground">{c.cluster_summary ?? c.domain_name ?? c.cluster_id}</div><CoverageBar value={Math.round((c.cluster_confidence ?? 0) * 100)} className="mt-2" /></div>))}</div>) : "No dependencies available."}</TabsContent></Tabs></CardContent></Card></div></div>);
}
