/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SemanticsRouteImport } from './routes/semantics'
import { Route as RelationshipsRouteImport } from './routes/relationships'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as ReadinessHistoryRouteImport } from './routes/readiness-history'
import { Route as PromptStudioRouteImport } from './routes/prompt-studio'
import { Route as PromptBudgetsRouteImport } from './routes/prompt-budgets'
import { Route as KpiRouteImport } from './routes/kpi'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as EmbeddingsRouteImport } from './routes/embeddings'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SemanticsRoute = SemanticsRouteImport.update({
  id: '/semantics',
  path: '/semantics',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessHistoryRoute = ReadinessHistoryRouteImport.update({
  id: '/readiness-history',
  path: '/readiness-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptStudioRoute = PromptStudioRouteImport.update({
  id: '/prompt-studio',
  path: '/prompt-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptBudgetsRoute = PromptBudgetsRouteImport.update({
  id: '/prompt-budgets',
  path: '/prompt-budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiRoute = KpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddingsRoute = EmbeddingsRouteImport.update({
  id: '/embeddings',
  path: '/embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/embeddings': typeof EmbeddingsRoute
  '/agents': typeof AgentsRoute
  '/explorer': typeof ExplorerRoute
  '/governance': typeof GovernanceRoute
  '/jobs': typeof JobsRoute
  '/kpi': typeof KpiRoute
  '/prompt-studio': typeof PromptStudioRoute
  '/prompt-budgets': typeof PromptBudgetsRoute
  '/readiness': typeof ReadinessRoute
  '/readiness-history': typeof ReadinessHistoryRoute
  '/relationships': typeof RelationshipsRoute
  '/semantics': typeof SemanticsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/embeddings': typeof EmbeddingsRoute
  '/agents': typeof AgentsRoute
  '/explorer': typeof ExplorerRoute
  '/governance': typeof GovernanceRoute
  '/jobs': typeof JobsRoute
  '/kpi': typeof KpiRoute
  '/prompt-studio': typeof PromptStudioRoute
  '/prompt-budgets': typeof PromptBudgetsRoute
  '/readiness': typeof ReadinessRoute
  '/readiness-history': typeof ReadinessHistoryRoute
  '/relationships': typeof RelationshipsRoute
  '/semantics': typeof SemanticsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/embeddings': typeof EmbeddingsRoute
  '/agents': typeof AgentsRoute
  '/explorer': typeof ExplorerRoute
  '/governance': typeof GovernanceRoute
  '/jobs': typeof JobsRoute
  '/kpi': typeof KpiRoute
  '/prompt-studio': typeof PromptStudioRoute
  '/prompt-budgets': typeof PromptBudgetsRoute
  '/readiness': typeof ReadinessRoute
  '/readiness-history': typeof ReadinessHistoryRoute
  '/relationships': typeof RelationshipsRoute
  '/semantics': typeof SemanticsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/embeddings'
    | '/agents'
    | '/explorer'
    | '/governance'
    | '/jobs'
    | '/kpi'
    | '/prompt-studio'
    | '/prompt-budgets'
    | '/readiness'
    | '/readiness-history'
    | '/relationships'
    | '/semantics'
    | '/settings'
    | '/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/embeddings'
    | '/agents'
    | '/explorer'
    | '/governance'
    | '/jobs'
    | '/kpi'
    | '/prompt-studio'
    | '/prompt-budgets'
    | '/readiness'
    | '/readiness-history'
    | '/relationships'
    | '/semantics'
    | '/settings'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/embeddings'
    | '/agents'
    | '/explorer'
    | '/governance'
    | '/jobs'
    | '/kpi'
    | '/prompt-studio'
    | '/readiness'
    | '/relationships'
    | '/semantics'
    | '/settings'
    | '/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  EmbeddingsRoute: typeof EmbeddingsRoute
  AgentsRoute: typeof AgentsRoute
  ExplorerRoute: typeof ExplorerRoute
  GovernanceRoute: typeof GovernanceRoute
  JobsRoute: typeof JobsRoute
  KpiRoute: typeof KpiRoute
  PromptStudioRoute: typeof PromptStudioRoute
  PromptBudgetsRoute: typeof PromptBudgetsRoute
  ReadinessRoute: typeof ReadinessRoute
  ReadinessHistoryRoute: typeof ReadinessHistoryRoute
  RelationshipsRoute: typeof RelationshipsRoute
  SemanticsRoute: typeof SemanticsRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semantics': {
      id: '/semantics'
      path: '/semantics'
      fullPath: '/semantics'
      preLoaderRoute: typeof SemanticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness-history': {
      id: '/readiness-history'
      path: '/readiness-history'
      fullPath: '/readiness-history'
      preLoaderRoute: typeof ReadinessHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-studio': {
      id: '/prompt-studio'
      path: '/prompt-studio'
      fullPath: '/prompt-studio'
      preLoaderRoute: typeof PromptStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-budgets': {
      id: '/prompt-budgets'
      path: '/prompt-budgets'
      fullPath: '/prompt-budgets'
      preLoaderRoute: typeof PromptBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi': {
      id: '/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof KpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embeddings': {
      id: '/embeddings'
      path: '/embeddings'
      fullPath: '/embeddings'
      preLoaderRoute: typeof EmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  EmbeddingsRoute: EmbeddingsRoute,
  ExplorerRoute: ExplorerRoute,
  GovernanceRoute: GovernanceRoute,
  JobsRoute: JobsRoute,
  KpiRoute: KpiRoute,
  PromptStudioRoute: PromptStudioRoute,
  PromptBudgetsRoute: PromptBudgetsRoute,
  ReadinessRoute: ReadinessRoute,
  RelationshipsRoute: RelationshipsRoute,
  SemanticsRoute: SemanticsRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
