export const queryKeys = {
  connections: () => ["connections"],
  dashboard: (databaseId: number | string) => ["dashboard", databaseId],
  databases: () => ["databases"],
  pipeline: () => ["pipeline"],
  observability: () => ["observability"],
  health: () => ["health"],
  jobs: (statusFilter: string) => ["jobs", statusFilter],
  syncLogs: (databaseId: number | string, limit: number) => ["sync-logs", databaseId, limit],
  syncLogsAll: () => ["sync-logs"],
  schemas: (databaseId: number | string) => ["schemas", databaseId],
  tables: (schemaId: number | string) => ["tables", schemaId],
  columns: (tableId: number | string) => ["columns", tableId],
  relationshipsByTable: (tableId: number | string) => ["relationships", tableId],
  diagnose: (databaseId: number | string) => ["diagnose", databaseId],
  observabilityTraces: (databaseId: number | string, filtersKey: string) => ["observability-traces", databaseId, filtersKey],
  observabilityTraceDetail: (databaseId: number | string, traceId: string) => ["observability-trace-detail", databaseId, traceId],
  observabilityLifecycleEvents: (databaseId: number | string) => ["observability-lifecycle-events", databaseId],
  governance: (databaseId: number | string) => ["governance", databaseId],
  governanceSummary: (databaseId: number | string) => ["governance-summary", databaseId],
  governanceEvidence: (tableId: number | string | null | undefined) => ["governance-evidence", tableId ?? "none"],
  semantics: (databaseId: number | string) => ["semantics", databaseId],
  semanticEvidence: (databaseId: number | string) => ["semantic-evidence", databaseId],
  relationships: (databaseId: number | string) => ["relationships", databaseId],
  kpi: (databaseId: number | string) => ["kpi", databaseId],
  promptTemplates: () => ["prompt-templates"],
  promptInventory: () => ["prompt-inventory"],
  promptBundle: (databaseId: number | string) => ["prompt-bundle", databaseId],
  promptPackages: (databaseId: number | string) => ["prompt-packages", databaseId],
  promptVersions: (promptPackageId: number | string | null | undefined) => ["prompt-versions", promptPackageId ?? "none"],
  promptObservability: (promptPackageId: number | string | null | undefined) => ["prompt-observability", promptPackageId ?? "none"],
  embeddings: (databaseId: number | string) => ["embeddings", databaseId],
  retrievalMetrics: (databaseId: number | string) => ["retrieval", "metrics", databaseId],
  retrievalSearch: (databaseId: number | string, query: string, topK: number) => ["retrieval-search", databaseId, query, topK],
  retrievalGraph: (databaseId: number | string, query: string, depth: number, maxPaths: number) => ["retrieval-graph", databaseId, query, depth, maxPaths],
  retrievalRegistry: () => ["retrieval-registry"],
  retrievalEvaluation: (databaseId: number | string) => ["retrieval-evaluation", databaseId],
  agentMemoryHistory: (databaseId: number | string, limit: number) => ["agent-memory-history", databaseId, limit],
  agentMemorySearch: (databaseId: number | string, query: string, topK: number) => ["agent-memory-search", databaseId, query, topK],
  agentMemoryHealth: (databaseId: number | string) => ["agent-memory-health", databaseId],
  readiness: (databaseId: number | string) => ["readiness", databaseId],
  readinessHistory: (databaseId: number | string, maturityLevel: string, minScore: number | string, maxScore: number | string) => [
    "readiness-history",
    databaseId,
    maturityLevel,
    minScore,
    maxScore,
  ],
  pipelineExecutions: (databaseId: number | string, limit: number) => ["pipeline-executions", databaseId, limit],
  stageExecutions: (databaseId: number | string, pipelineExecutionId: number | string, limit: number) => [
    "stage-executions",
    databaseId,
    pipelineExecutionId,
    limit,
  ],
  businessIntelligence: {
    opportunities: (databaseId: number | string) => ["business-intelligence", "opportunities", databaseId],
    dataProducts: (databaseId: number | string) => ["business-intelligence", "data-products", databaseId],
    warehouseDesigns: (databaseId: number | string) => ["business-intelligence", "warehouse-designs", databaseId],
    recommendations: (databaseId: number | string) => ["business-intelligence", "recommendations", databaseId],
    predictiveReadiness: (databaseId: number | string) => ["business-intelligence", "predictive-readiness", databaseId],
    health: (databaseId: number | string) => ["business-intelligence", "health", databaseId],
  },
  businessEvents: (databaseId: number | string) => ["business-events", databaseId],
  businessEventsHealth: (databaseId: number | string) => ["business-events-health", databaseId],
};
